# Generated by Django 5.1.6 on 2025-10-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='conorder',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee'),
        ),
    ]
