# Generated by Django 5.1.6 on 2025-10-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_conorder_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_krill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_krill',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
